// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['service']['environmentSvc']['Close']();
}

export function Init(arg1) {
  return window['go']['service']['environmentSvc']['Init'](arg1);
}
