// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {context} from '../models';

export function Close():Promise<void>;

export function GetTabSession():Promise<model.TabSession>;

export function Init(arg1:context.Context):Promise<void>;

export function SetTabSession(arg1:model.TabSession):Promise<void>;
