// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['service']['sessionSvc']['Close']();
}

export function GetTabSession() {
  return window['go']['service']['sessionSvc']['GetTabSession']();
}

export function Init(arg1) {
  return window['go']['service']['sessionSvc']['Init'](arg1);
}

export function SetTabSessionPosition(arg1, arg2) {
  return window['go']['service']['sessionSvc']['SetTabSessionPosition'](arg1, arg2);
}

export function SetTabSessionTabs(arg1) {
  return window['go']['service']['sessionSvc']['SetTabSessionTabs'](arg1);
}
