// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Close():Promise<void>;

export function GetRootDir():Promise<string>;

export function Init(arg1:context.Context):Promise<void>;
