// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['service']['systemSvc']['Close']();
}

export function GetRootDir() {
  return window['go']['service']['systemSvc']['GetRootDir']();
}

export function Init(arg1) {
  return window['go']['service']['systemSvc']['Init'](arg1);
}
